# For DiligentCore
find_package(SPIRV-Headers REQUIRED CONFIG)
find_package(SPIRV-Tools REQUIRED CONFIG)
find_package(spirv-cross REQUIRED CONFIG)
find_package(volk REQUIRED CONFIG)
find_package(xxHash REQUIRED CONFIG)
find_package(GLEW REQUIRED CONFIG)

# For DiligentTools
find_package(args REQUIRED CONFIG)
find_package(JPEG REQUIRED CONFIG)
find_package(nlohmann_json REQUIRED CONFIG)
find_package(PNG REQUIRED CONFIG)
find_package(stb REQUIRED CONFIG)
find_package(TIFF REQUIRED CONFIG)
find_package(TinyGLTF REQUIRED CONFIG)
find_package(ZLIB REQUIRED CONFIG)

if(NOT DILIGENT_NO_GLSLANG)
    find_package(glslang REQUIRED CONFIG)
    add_library(glslang INTERFACE)
    target_link_libraries(glslang INTERFACE glslang::glslang)
    target_include_directories(glslang INTERFACE ${glslang_INCLUDE_DIR}/glslang)
    add_library(SPIRV ALIAS glslang::SPIRV)
endif()

add_library(SPIRV-Headers ALIAS SPIRV-Headers::SPIRV-Headers)
add_library(spirv-tools-core ALIAS SPIRV-Tools)
if(TARGET spirv-cross-c-shared)
    add_library(spirv-cross-core ALIAS spirv-cross-c-shared)
    add_library(spirv-cross-glsl ALIAS spirv-cross-c-shared)
    add_library(spirv-cross-msl ALIAS spirv-cross-c-shared)
endif()
