find_package(diligent-core REQUIRED CONFIG)
find_package(args REQUIRED CONFIG)
find_package(JPEG REQUIRED CONFIG)
find_package(nlohmann_json REQUIRED CONFIG)
find_package(PNG REQUIRED CONFIG)
find_package(stb REQUIRED CONFIG)
find_package(TIFF REQUIRED CONFIG)
find_package(TinyGLTF REQUIRED CONFIG)
find_package(ZLIB REQUIRED CONFIG)

list(GET diligent-core_INCLUDE_DIRS 0 CORE_INCLUDE_DIR)
set(Diligent-GraphicsEngine_SOURCE_DIR ${CORE_INCLUDE_DIR}/Graphics/GraphicsEngine)

add_library(Diligent-BuildSettings               ALIAS diligent-core::diligent-core)
add_library(Diligent-Common                      ALIAS diligent-core::diligent-core)
add_library(Diligent-PlatformInterface           ALIAS diligent-core::diligent-core)
add_library(Diligent-GraphicsEngineInterface     ALIAS diligent-core::diligent-core)
add_library(Diligent-GraphicsAccessories         ALIAS diligent-core::diligent-core)
add_library(Diligent-GraphicsTools               ALIAS diligent-core::diligent-core)
add_library(Diligent-Archiver-static             ALIAS diligent-core::diligent-core)
add_library(Diligent-HLSL2GLSLConverterLib       ALIAS diligent-core::diligent-core)
add_library(Diligent-TargetPlatform              ALIAS diligent-core::diligent-core)
add_library(Diligent-GraphicsEngineOpenGL-static ALIAS diligent-core::diligent-core)
